/**
 * Default life-event templates with AU-realistic ranges.
 * Numbers are illustrative planning estimates only.
 */
import type { LifeEventTemplate, LifeEventId } from './types';

export const LIFE_EVENT_TEMPLATES: Record<LifeEventId, LifeEventTemplate> = {
  child_birth: {
    id: 'child_birth',
    category: 'family',
    label: 'Child — birth',
    description: 'First-year baby costs: hospital + gear + lower income.',
    defaultMonthlyExpenseDelta: 900,
    defaultAnnualIncomeDelta: -25000,
    defaultOneTimeCost: 8000,
    defaultDurationMonths: 12,
    stressProbability: 0.4,
    considerations: ['Parental leave duration', 'Single vs dual-income impact', 'Health cover'],
  },
  additional_child: {
    id: 'additional_child',
    category: 'family',
    label: 'Additional child',
    description: 'Recurring costs from another dependant.',
    defaultMonthlyExpenseDelta: 750,
    defaultAnnualIncomeDelta: -18000,
    defaultOneTimeCost: 6000,
    defaultDurationMonths: 18,
    stressProbability: 0.3,
    considerations: ['Childcare overlap', 'Housing space needs'],
  },
  childcare_change: {
    id: 'childcare_change',
    category: 'family',
    label: 'Childcare change',
    description: 'Daycare / nanny costs or transition into school.',
    defaultMonthlyExpenseDelta: 1800,
    defaultAnnualIncomeDelta: 0,
    defaultOneTimeCost: 0,
    defaultDurationMonths: 48,
    stressProbability: 0.5,
    considerations: ['Childcare subsidy', 'Centre vs in-home cost'],
  },
  school_costs: {
    id: 'school_costs',
    category: 'family',
    label: 'School costs',
    description: 'Private/public school fees, uniforms, extracurricular.',
    defaultMonthlyExpenseDelta: 1500,
    defaultAnnualIncomeDelta: 0,
    defaultOneTimeCost: 3000,
    defaultDurationMonths: 144, // K-12
    stressProbability: 0.3,
    considerations: ['Public vs private decision', 'Siblings stacking'],
  },
  university_funding: {
    id: 'university_funding',
    category: 'family',
    label: 'University funding',
    description: 'Support for child(ren) at university.',
    defaultMonthlyExpenseDelta: 1000,
    defaultAnnualIncomeDelta: 0,
    defaultOneTimeCost: 0,
    defaultDurationMonths: 48,
    stressProbability: 0.2,
    considerations: ['HELP loan vs cash funding', 'Living away from home'],
  },
  parental_care: {
    id: 'parental_care',
    category: 'family',
    label: 'Parental care',
    description: 'Financial support for ageing parents.',
    defaultMonthlyExpenseDelta: 800,
    defaultAnnualIncomeDelta: 0,
    defaultOneTimeCost: 5000,
    defaultDurationMonths: 60,
    stressProbability: 0.3,
    considerations: ['Aged care levy', 'In-home support cost'],
  },
  job_loss: {
    id: 'job_loss',
    category: 'career',
    label: 'Job loss',
    description: 'Temporary loss of primary earner income.',
    defaultMonthlyExpenseDelta: 0,
    defaultAnnualIncomeDelta: -110000,
    defaultOneTimeCost: 0,
    defaultDurationMonths: 6,
    stressProbability: 0.5,
    considerations: ['Buffer runway', 'Loan repayment holiday options'],
  },
  income_shock: {
    id: 'income_shock',
    category: 'career',
    label: 'Income shock',
    description: 'Partial income reduction (bonus loss, hours cut).',
    defaultMonthlyExpenseDelta: 0,
    defaultAnnualIncomeDelta: -30000,
    defaultOneTimeCost: 0,
    defaultDurationMonths: 12,
    stressProbability: 0.4,
    considerations: ['Cashflow tightening', 'Borrowing capacity impact'],
  },
  career_upgrade: {
    id: 'career_upgrade',
    category: 'career',
    label: 'Career upgrade',
    description: 'Promotion or new role boosting income.',
    defaultMonthlyExpenseDelta: 200,
    defaultAnnualIncomeDelta: 25000,
    defaultOneTimeCost: 0,
    defaultDurationMonths: 0,
    stressProbability: 0,
    considerations: ['Tax bracket creep', 'Super contributions cap impact'],
  },
  moving_house: {
    id: 'moving_house',
    category: 'housing',
    label: 'Moving house',
    description: 'Relocating with associated transaction costs.',
    defaultMonthlyExpenseDelta: 0,
    defaultAnnualIncomeDelta: 0,
    defaultOneTimeCost: 12000,
    defaultDurationMonths: 0,
    stressProbability: 0.2,
    considerations: ['Stamp duty', 'Bridging finance'],
  },
  upsizing: {
    id: 'upsizing',
    category: 'housing',
    label: 'Upsizing',
    description: 'Larger home — higher mortgage and running costs.',
    defaultMonthlyExpenseDelta: 1500,
    defaultAnnualIncomeDelta: 0,
    defaultOneTimeCost: 45000,
    defaultDurationMonths: 0,
    stressProbability: 0.25,
    considerations: ['Higher rates + insurance', 'Reduced surplus for investing'],
  },
  downsizing: {
    id: 'downsizing',
    category: 'housing',
    label: 'Downsizing',
    description: 'Smaller home — frees up equity.',
    defaultMonthlyExpenseDelta: -800,
    defaultAnnualIncomeDelta: 0,
    defaultOneTimeCost: 20000,
    defaultDurationMonths: 0,
    stressProbability: 0.1,
    considerations: ['Downsizer super contribution rules', 'CGT main-residence rules'],
  },
  retirement_transition: {
    id: 'retirement_transition',
    category: 'retirement',
    label: 'Retirement transition',
    description: 'Switching from employment to retirement income streams.',
    defaultMonthlyExpenseDelta: 0,
    defaultAnnualIncomeDelta: -90000,
    defaultOneTimeCost: 0,
    defaultDurationMonths: 0,
    stressProbability: 0.1,
    considerations: ['Drawdown strategy', 'Bridge years before super preservation age'],
  },
  semi_retirement: {
    id: 'semi_retirement',
    category: 'retirement',
    label: 'Semi-retirement',
    description: 'Reduced hours with partial income.',
    defaultMonthlyExpenseDelta: 0,
    defaultAnnualIncomeDelta: -50000,
    defaultOneTimeCost: 0,
    defaultDurationMonths: 0,
    stressProbability: 0.1,
    considerations: ['Healthcare', 'Investment income smoothing'],
  },
  inheritance: {
    id: 'inheritance',
    category: 'wealth_transfer',
    label: 'Inheritance',
    description: 'One-off inflow from estate.',
    defaultMonthlyExpenseDelta: 0,
    defaultAnnualIncomeDelta: 0,
    defaultOneTimeCost: -150000, // inflow
    defaultDurationMonths: 0,
    stressProbability: 0,
    considerations: ['Capital gains cost base', 'Asset allocation'],
  },
  divorce_separation: {
    id: 'divorce_separation',
    category: 'family',
    label: 'Divorce / separation stress',
    description: 'Significant cashflow + asset split impact.',
    defaultMonthlyExpenseDelta: 1500,
    defaultAnnualIncomeDelta: -40000,
    defaultOneTimeCost: 25000,
    defaultDurationMonths: 24,
    stressProbability: 0.6,
    considerations: ['Asset split', 'Legal costs', 'Housing arrangements'],
  },
  health_event: {
    id: 'health_event',
    category: 'health',
    label: 'Health event',
    description: 'Significant medical or rehab cost.',
    defaultMonthlyExpenseDelta: 600,
    defaultAnnualIncomeDelta: -20000,
    defaultOneTimeCost: 15000,
    defaultDurationMonths: 12,
    stressProbability: 0.5,
    considerations: ['Income protection cover', 'PHI vs Medicare'],
  },
  reduced_work_capacity: {
    id: 'reduced_work_capacity',
    category: 'health',
    label: 'Reduced work capacity',
    description: 'Long-term reduction in earnings ability.',
    defaultMonthlyExpenseDelta: 0,
    defaultAnnualIncomeDelta: -35000,
    defaultOneTimeCost: 0,
    defaultDurationMonths: 60,
    stressProbability: 0.4,
    considerations: ['TPD / IP claim', 'Super disability options'],
  },
};

export function listLifeEventTemplates(): LifeEventTemplate[] {
  return Object.values(LIFE_EVENT_TEMPLATES);
}
