import type { MacroRegimeDefinition, MacroRegimeId } from './types';

/**
 * Macro regime catalogue — calibrated for AUS households.
 * Default probabilities sum to ~1.0 and are renormalised when subsets are
 * used. Magnitudes are conservative deltas over a multi-year horizon.
 */
export const MACRO_REGIMES: Record<MacroRegimeId, MacroRegimeDefinition> = {
  inflation_spike: {
    id: 'inflation_spike',
    label: 'Inflation spike',
    description: 'Persistent CPI well above target. Real returns compress.',
    defaultProbability: 0.07,
    impact: {
      inflationDelta: 0.03,
      etfReturnDelta: -0.015,
      cryptoReturnDelta: -0.02,
      rentGrowthDelta: 0.03,
      interestRateDelta: 0.015,
      expensesMultiplier: 1.05,
      serviceabilityDelta: -0.05,
      liquidityRiskDelta: 0.05,
      fireTimelineYearsDelta: 1.0,
    },
    keyDriver: 'CPI > 5%',
  },
  inflation_collapse: {
    id: 'inflation_collapse',
    label: 'Inflation collapse',
    description: 'CPI falls below target — real returns boosted, rates cut.',
    defaultProbability: 0.04,
    impact: {
      inflationDelta: -0.02,
      etfReturnDelta: 0.01,
      interestRateDelta: -0.01,
      fireTimelineYearsDelta: -0.3,
    },
    keyDriver: 'CPI < 1.5%',
  },
  rate_cuts: {
    id: 'rate_cuts',
    label: 'Rate-cut cycle',
    description: 'Central bank easing — asset valuations expand, debt servicing eases.',
    defaultProbability: 0.12,
    impact: {
      interestRateDelta: -0.015,
      propertyGrowthDelta: 0.02,
      etfReturnDelta: 0.02,
      serviceabilityDelta: 0.05,
      fireTimelineYearsDelta: -0.5,
    },
    keyDriver: 'RBA cuts ≥ 75bps',
  },
  rate_hikes: {
    id: 'rate_hikes',
    label: 'Rate-hike cycle',
    description: 'Tightening monetary conditions — leverage costs more, growth slows.',
    defaultProbability: 0.08,
    impact: {
      interestRateDelta: 0.015,
      propertyGrowthDelta: -0.015,
      etfReturnDelta: -0.01,
      serviceabilityDelta: -0.05,
      fireTimelineYearsDelta: 0.4,
      liquidityRiskDelta: 0.05,
    },
    keyDriver: 'RBA hikes ≥ 75bps',
  },
  recession: {
    id: 'recession',
    label: 'Recession',
    description: 'Two consecutive quarters of contraction. Earnings and rents wobble.',
    defaultProbability: 0.07,
    impact: {
      etfReturnDelta: -0.03,
      propertyGrowthDelta: -0.02,
      rentGrowthDelta: -0.01,
      unemploymentProbDelta: 0.1,
      liquidityRiskDelta: 0.1,
      fireTimelineYearsDelta: 1.0,
    },
    keyDriver: 'GDP -2qtrs',
  },
  stagflation: {
    id: 'stagflation',
    label: 'Stagflation',
    description: 'Stagnant growth with persistent inflation. The worst regime for portfolios.',
    defaultProbability: 0.03,
    impact: {
      etfReturnDelta: -0.025,
      cryptoReturnDelta: -0.03,
      inflationDelta: 0.025,
      interestRateDelta: 0.01,
      expensesMultiplier: 1.05,
      serviceabilityDelta: -0.08,
      fireTimelineYearsDelta: 1.5,
      liquidityRiskDelta: 0.1,
    },
    keyDriver: 'CPI > 4% + GDP < 1%',
  },
  ai_boom: {
    id: 'ai_boom',
    label: 'AI productivity boom',
    description: 'Sustained productivity gains lift equity returns and wages.',
    defaultProbability: 0.05,
    impact: {
      etfReturnDelta: 0.025,
      cryptoReturnDelta: 0.02,
      fireTimelineYearsDelta: -1.0,
    },
    keyDriver: 'productivity > 2%',
  },
  property_downturn: {
    id: 'property_downturn',
    label: 'Property downturn',
    description: 'Sustained AUS housing correction (price falls > 10%).',
    defaultProbability: 0.06,
    impact: {
      propertyGrowthDelta: -0.04,
      rentGrowthDelta: -0.005,
      liquidityRiskDelta: 0.05,
      fireTimelineYearsDelta: 0.5,
    },
    keyDriver: 'capital city index -10%',
  },
  property_supercycle: {
    id: 'property_supercycle',
    label: 'Property supercycle',
    description: 'Supply-demand imbalance + immigration lifts AUS property growth multi-year.',
    defaultProbability: 0.05,
    impact: {
      propertyGrowthDelta: 0.03,
      rentGrowthDelta: 0.02,
      fireTimelineYearsDelta: -0.5,
    },
    keyDriver: 'AUS net migration > 350k/yr',
  },
  equity_bull: {
    id: 'equity_bull',
    label: 'Equity bull market',
    description: 'Risk-on backdrop. ETF expected returns above trend.',
    defaultProbability: 0.10,
    impact: {
      etfReturnDelta: 0.03,
      cryptoReturnDelta: 0.05,
      fireTimelineYearsDelta: -0.6,
    },
    keyDriver: 'S&P/ASX > 12mo MA',
  },
  equity_crash: {
    id: 'equity_crash',
    label: 'Equity crash',
    description: 'Drawdown of 25%+ in major indices.',
    defaultProbability: 0.07,
    impact: {
      etfReturnDelta: -0.06,
      cryptoReturnDelta: -0.15,
      liquidityRiskDelta: 0.05,
      fireTimelineYearsDelta: 1.0,
    },
    keyDriver: 'Index -25%',
  },
  crypto_winter: {
    id: 'crypto_winter',
    label: 'Crypto winter',
    description: 'Multi-year bear cycle in digital assets.',
    defaultProbability: 0.05,
    impact: {
      cryptoReturnDelta: -0.1,
    },
    keyDriver: 'BTC -50%',
  },
  crypto_supercycle: {
    id: 'crypto_supercycle',
    label: 'Crypto supercycle',
    description: 'Sustained adoption wave. High variance, high upside.',
    defaultProbability: 0.04,
    impact: {
      cryptoReturnDelta: 0.2,
      fireTimelineYearsDelta: -0.3,
    },
    keyDriver: 'BTC > prior ATH × 1.5',
  },
  employment_shock: {
    id: 'employment_shock',
    label: 'Employment shock',
    description: 'Job loss or material income disruption.',
    defaultProbability: 0.05,
    impact: {
      unemploymentProbDelta: 0.25,
      liquidityRiskDelta: 0.2,
      fireTimelineYearsDelta: 1.5,
    },
    keyDriver: 'income disruption',
  },
  strong_wage_growth: {
    id: 'strong_wage_growth',
    label: 'Strong wage growth',
    description: 'Real wage growth lifts saving and serviceability.',
    defaultProbability: 0.06,
    impact: {
      serviceabilityDelta: 0.05,
      fireTimelineYearsDelta: -0.4,
    },
    keyDriver: 'WPI > 4%',
  },
};
